# TIPO BOOLEANO NO PYTHON - BOOLEAN(VALORES TRUE FALSE) - VERDADE OU FALSE
# TIPO BOOLEAN REPRESENTA UM VALOR VERDADEIRO OU FALSO

variavel = True

print(variavel)

# UMA MANEIRA DE GERAR VALORES TRUE E FALSE PARA O BOOLEAN E USANDO EXPRESSÕES LOGICAS QUE RESULTAM EM VALORES LOGICOS(TRUE OU FALSE)
# FAÇO UMA EXPRESSÃO LOGICA PERGUNTANDO SE 100 E MAIOR QUE 0

resultado = 100 > 0
print(resultado)

# POSSO FAZER UM CAST ENTRE STRING E BOOLEAN, COM ISSO EU CONSIGO SABER SE UMA STRING E VAZIO OU NÃO

stringTexto = "Possui texto"

print("A string possui texto ?");print(bool(stringTexto))

# ISSO PODE SER FEITO COM QUALQUER VARIAVEL, COM QUALQUER VALOR DENTRO DE UM VARIAVEL DE QUALQUER TIPO, QUE SEJA DIFERENTE DE 0, QUALQUER VALOR DIFERENTE DE 0 E CONSIDERADO TRUE.

numero = 10; salario = 100.90; 
print("variavel numero e vazio ?: "); print(bool(numero))
print("variavel salario e vazio ?: "); print(bool(salario))     